#!/bin/bash
################################################################################
# Copyright 2012 Robert C. Curtis. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#    1. Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#    2. Redistributions in binary form must reproduce the above
#       copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials
#       provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY ROBERT C. CURTIS ``AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL ROBERT C. CURTIS OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
# OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
# USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
# DAMAGE.
#
# The views and conclusions contained in the software and documentation
# are those of the authors and should not be interpreted as representing
# official policies, either expressed or implied, of Robert C. Curtis.
################################################################################

BARTVERSION=DEV

# Color constants
NO="\033[0m"
BR="\033[30m"
RD="\033[31m"
GR="\033[32m"
YL="\033[33m"
BL="\033[34m"
MG="\033[35m"
CY="\033[36m"

# Usage command
usage () {
	echo "usage: bart [OPTIONS] <repository>"
	echo "OPTIONS:"
	echo "  -h, --help      Print usage"
	echo "  --version       Print version"
	echo "  --tag           Tag revision is build succeeds"
	echo "  --release       Run the release phase of the build"
	echo "  --branch        Specify branch to checkout"
}

# Error command
error () {
    echo -e "[ERROR]" $* 1>&2
}

# Warning command
warn () {
    echo -e "[WARNING]" $* 1>&2
}

# Defaults
TAG=0
SCM=GIT
RELEASE=0
BRANCH=
BUILDSUCCESS=0

# Handle Options
while [ "${1:0:1}" == "-" ]; do
	# Help
	if [ "$1" == "-h" -o "$1" == "--help" ]; then
		usage
		exit 0
	fi
	# Version
	if [ "$1" == "--version" ]; then
		echo "$BARTVERSION"
		exit 0
	fi
	# Tag
	if [ "$1" == "--tag" ]; then
		TAG=1
		shift && continue
	fi
	# Release
	if [ "$1" == "--release" ]; then
		RELEASE=1
		shift && continue
	fi
	# Branch
	if [ "$1" == "--branch" ]; then
		shift
		BRANCH=$1
		shift && continue
	fi
	warn "Unrecognized option: $1"
	shift
done
# if no arguments, print usage
if [ "$#" -eq 0 ]; then
    usage
    exit 1
fi
REPO="$1"
shift

# Create a Temporary Directory Name
TMPREPO=$(mktemp -d -t bart)
if [ -n "$TMPREPO" ]; then
	trap "rm -rf $TMPREPO" EXIT
fi

# Check out repository
if [ "$SCM" == "GIT" ]; then
	BR_OPT=""
	if [ -n "$BRANCH" ]; then
		BR_OPT="-b $BRANCH"
	fi
	git clone $BR_OPT "$REPO" "$TMPREPO"
else
	error "Unknown SCM type"
	exit 1
fi

# Source the repo's .bart file
source "${TMPREPO}/.bart"
if [ $? -eq 1 ]; then
	error "Repository does not seem to have a .bart file"
	exit 1
fi

# Tag repository
if [ "$TAG" -eq 1 ]; then
	echo TAG
fi

# Pre Build

# Build

# Post Build

# Package

# Release

