#!/bin/bash
################################################################################
# Copyright 2012 Robert C. Curtis. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#    1. Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#    2. Redistributions in binary form must reproduce the above
#       copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials
#       provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY ROBERT C. CURTIS ``AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL ROBERT C. CURTIS OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
# OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
# USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
# DAMAGE.
#
# The views and conclusions contained in the software and documentation
# are those of the authors and should not be interpreted as representing
# official policies, either expressed or implied, of Robert C. Curtis.
################################################################################

BARTVERSION=DEV

# Color constants
NO="\033[0m"
BR="\033[30m"
RD="\033[31m"
GR="\033[32m"
YL="\033[33m"
BL="\033[34m"
MG="\033[35m"
CY="\033[36m"

# Usage command
usage () {
	echo "usage: bartbot [OPTIONS] <project file>"
	echo "OPTIONS:"
	echo "  -h, --help      Print usage"
	echo "  --version       Print version"
	echo "  --tag           Tag revision if build succeeds"
	echo "  --settag <>     Use supplied tag instead of generated tag"
	echo "  --release       Run the release phase of the build"
	echo "  --init <repo>   Create a new project file"
}

# Error command
error () {
    echo -e "[ERROR]" $* 1>&2
}

# Warning command
warn () {
    echo -e "[WARNING]" $* 1>&2
}

# Info command
info () {
    echo -e "[INFO]" $* 1>&2
}

# Defaults
TAGOPT=
SETTAGOPT=
RELEASEOPT=
DOTFILEOPT=
INITPRJ=0
REPO=

# Handle Options
while [ "${1:0:1}" == "-" ]; do
	# Help
	if [ "$1" == "-h" -o "$1" == "--help" ]; then
		usage
		exit 0
	fi
	# Version
	if [ "$1" == "--version" ]; then
		echo "$BARTVERSION"
		exit 0
	fi
	# Tag
	if [ "$1" == "--tag" ]; then
		TAGOPT="--tag"
		shift && continue
	fi
	# Set Tag
	if [ "$1" == "--settag" ]; then
		shift
		SETTAGOPT="--settag $1"
		shift && continue
	fi
	# Release
	if [ "$1" == "--release" ]; then
		RELEASEOPT="--release"
		shift && continue
	fi
	# Init
	if [ "$1" == "--init" ]; then
		shift
		INITPRJ=1
		REPO=$1
		shift && continue
	fi
	warn "Unrecognized option: $1"
	shift
done
# if no arguments, print usage
if [ "$#" -eq 0 ]; then
    usage
    exit 1
fi
PRJFILE="$1"
shift

# Run init if necessary
if [ "$INITPRJ" -eq 1 ]; then
	if [ -e "$PRJFILE" ]; then
		error "Project file already exists"
		exit 1
	fi
	echo "REPO=\"${REPO}\"" > "$PRJFILE"
	if [ $? -ne 0 ]; then
		error "Could not create project file"
		exit 1
	fi
	echo "BRANCH=master" >> "$PRJFILE"
	echo "DESTDIR=$(dirname $PRJFILE)" >> "$PRJFILE"
	echo "LASTBUILD=" >> "$PRJFILE"
	echo "DOTFILE=" >> "$PRJFILE"
	exit 0
fi

if [ ! -f "$PRJFILE" ]; then
	error "Project file does not exist"
fi

source "$PRJFILE"

if [ -z "$REPO" ]; then
	error "REPO not set"
	exit 1
fi
if [ -z "$BRANCH" ]; then
	error "BRANCH not set"
	exit 1
fi
if [ ! -d "$DESTDIR" ]; then
	error "DESTDIR does not exist"
	exit 1
fi
if [ -n "$DOTFILE" ]; then
	DOTFILEOPT="--dotfile $DOTFILE"
fi

CURRENTCHANGE=$(bart --branch $BRANCH --head "$REPO")

if [ "$CURRENTCHANGE" == "$LASTBUILD" ]; then
	info "No new changes"
	exit 0
fi

pushd "$DESTDIR"
if [ $? -ne 0 ]; then
	error "Could not CD to DESTDIR"
	exit 1
fi
bart --branch $BRANCH $TAGOPT $SETTAGOPT $RELEASEOPT $DOTFILEOPT "$REPO"
if [ $? -ne 0 ]; then
	error "Build Failed"
	exit 1
fi

popd

# write out change to lastbuild
sed -i '' -e 's/^LASTBUILD=\(.*\)$/LASTBUILD='${CURRENTCHANGE}'/' "$PRJFILE"
